/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberosgrupo47.Vistas;

import bomberosgrupo47.accesoADatos.BomberoData;
import bomberosgrupo47.entidades.Bombero;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ConsultaDeBomberosPorBrigada extends javax.swing.JInternalFrame {
private DefaultTableModel modelo= new DefaultTableModel (){

    public boolean isCellEditable (int f, int c) {
    
        return false;
    }
};


    /**
     * Creates new form ConsultaDeBomberosPorBrigada
     */
    public ConsultaDeBomberosPorBrigada() {
        initComponents();
        armarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtcodBrig = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbomberos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jbBuscarBrigada = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Consulta de Bomberos por Brigada");

        jLabel2.setText("Escriba el \"Codigo\" de la \"Brigada\" que desea ver");

        jLabel3.setText("CODIGO:");

        jtcodBrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodBrigActionPerformed(evt);
            }
        });
        jtcodBrig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtcodBrigKeyReleased(evt);
            }
        });

        jtbomberos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbomberos.setSelectionForeground(new java.awt.Color(153, 255, 255));
        jScrollPane1.setViewportView(jtbomberos);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-al-menu-principal.jpeg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbBuscarBrigada.setText("BUSCAR");
        jbBuscarBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarBrigadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtcodBrig, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jbBuscarBrigada))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtcodBrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarBrigada))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtcodBrigKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcodBrigKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodBrigKeyReleased

    private void jtcodBrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodBrigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodBrigActionPerformed

    private void jbBuscarBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarBrigadaActionPerformed
        // BuscarBrigada (para ver los Bomberos):
        
        //con el ActionPerformed
        
        try{
            int code=Integer.parseInt(jtcodBrig.getText());
            BomberoData buscar=new BomberoData();
            Bombero bu=new Bombero();
          
            ArrayList<Bombero> list = new ArrayList<>();
            list=buscar.listarBomberosXbrig(code);
            eliminarLimpiar();
        for (int i = 0; i < list.size(); i++) {
                 

                 
                 
                    modelo.addRow(new Object[]{list.get(i).getIdBombero(),list.get(i).getDni(),list.get(i).getNombreApellido(),list.get(i).getFechaNac(),list.get(i).getCelular(),list.get(i).getBrigada()});
                    
                 
             
             }
           
            
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "Ingrese un Codigo Valido");
        }
        
    }//GEN-LAST:event_jbBuscarBrigadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscarBrigada;
    private javax.swing.JTable jtbomberos;
    private javax.swing.JTextField jtcodBrig;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("idBombero");
        modelo.addColumn("dni");
        modelo.addColumn("NombreApellido");
        modelo.addColumn("FechaNac");
        modelo.addColumn("Celular");
        modelo.addColumn("CodBrigada");
        jtbomberos.setModel(modelo);
    }
public void eliminarLimpiar(){
        DefaultTableModel tb = (DefaultTableModel) jtbomberos.getModel();
        int a = jtbomberos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
        tb.removeRow(tb.getRowCount()-1);
        }
        
    }
}
